package ui;

public enum Keyword {
    LOGIN, LOGOUT, SIGNUP, CHANGE_ACCOUNT_INFO, SHOWTOP10W, SHOWTOP10M, SHOWCATEGORIES, SHOWALLFILMS, SHOWBLURAY, SHOWLOGINPAGE, SHOWSIGNUPPAGE, SUBSCRIBE, RENT, RENTED_FILM , SHOWRETURNBLURAYPAGE, SHOWADVANCEDRESEARCH, MAINPAGE, BACK, SHOWFILMDETAILS, BLURAY_RETURNED
}
