package ui;

public enum Keyword {
    LOGIN, LOGOUT, SIGNUP, CHANGE_ACCOUNT_INFO, SHOWTOP10W, SHOWTOP10M, SHOWCATEGORIES, SHOWALLFILMS, SHOWBLURAY, SHOWLOGINPAGE, SUBSCRIBE, RENT, SHOWRETURNBLURAYPAGE, SHOWADVANCEDRESEARCH, MAINPAGE, SHOWFILMDETAILS, BLURAY_RETURNED
}
